version: "3.9"

services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails                 # Mount entire app for live code editing
      - ./storage/db:/rails/storage/db  # Persist SQLite files
      - bundle:/usr/local/bundle        # Persist installed gems
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  bundle:

