default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  default_transaction_mode: immediate

development:
  primary:
    <<: *default
    database: /rails/storage/db/development.sqlite3

test:
  primary:
    <<: *default
    database: /rails/storage/db/test.sqlite3

performance:
  primary:
    <<: *default
    database: /rails/storage/db/performance.sqlite3

production:
  primary:
    <<: *default
    database: /rails/storage/db/production.sqlite3

